export const theme = {
  colors: {
    light: {
      background: "#FAFBFC",
      foreground: "#0A0A0F",
      card: "#FFFFFF",
      cardForeground: "#0A0A0F",
      primary: "#6366F1",
      primaryForeground: "#FFFFFF",
      secondary: "#F1F5F9",
      secondaryForeground: "#0F172A",
      muted: "#F1F5F9",
      mutedForeground: "#64748B",
      accent: "#F1F5F9",
      accentForeground: "#0F172A",
      destructive: "#EF4444",
      destructiveForeground: "#FFFFFF",
      border: "#E2E8F0",
      input: "#E2E8F0",
      ring: "#6366F1",
      success: "#22C55E",
      warning: "#F59E0B",
      info: "#3B82F6",
      math: "#8B5CF6",
      physics: "#F97316",
      cs: "#06B6D4",
      engineering: "#10B981",
      general: "#6B7280",
    },
    dark: {
      background: "#0A0A0F",
      foreground: "#F8FAFC",
      card: "#111827",
      cardForeground: "#F8FAFC",
      primary: "#818CF8",
      primaryForeground: "#0A0A0F",
      secondary: "#1E293B",
      secondaryForeground: "#F8FAFC",
      muted: "#1E293B",
      mutedForeground: "#94A3B8",
      accent: "#1E293B",
      accentForeground: "#F8FAFC",
      destructive: "#F87171",
      destructiveForeground: "#0A0A0F",
      border: "#1E293B",
      input: "#1E293B",
      ring: "#818CF8",
      success: "#4ADE80",
      warning: "#FBBF24",
      info: "#60A5FA",
      math: "#A78BFA",
      physics: "#FB923C",
      cs: "#22D3EE",
      engineering: "#34D399",
      general: "#9CA3AF",
    },
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
    "3xl": "4rem",
  },
  borderRadius: {
    sm: "0.375rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    "2xl": "1.5rem",
  },
  fontFamily: {
    sans: "Inter, system-ui, sans-serif",
    mono: "JetBrains Mono, monospace",
    math: "KaTeX_Main, serif",
  },
} as const;

export type ThemeColors = typeof theme.colors.light;
